# Generated by Django 3.1 on 2021-02-25 09:24

from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200831_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=244)),
                ('country', models.CharField(max_length=244)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244)),
                ('description', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('image', pyuploadcare.dj.models.ImageField(blank=True)),
                ('categories', models.ManyToManyField(to='portfolio.Category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.location')),
            ],
        ),
    ]
